from enum import Enum

class AllureTag(str, Enum):
    COURSES = "COURSES"
    DASHBOARD = "DASHBOARD"
    REGRESSION = "REGRESSION"
    USER_LOGIN = "USER_LOGIN"
    NAVIGATION = "NAVIGATION"
    REGISTRATION = "REGISTRATION"
    USER_REGISTRATION = 'USER_REGISTRATION'
    AUTHORIZATION = "AUTHORIZATION"